apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: auth-demo
spec:
  podSelector: {}
  policyTypes: ["Ingress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rust-auth-sts-from-namespace
  namespace: auth-demo
spec:
  podSelector:
    matchLabels:
      app: rust-auth-sts
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: inventory-from-allowed-clients
  namespace: auth-demo
spec:
  podSelector:
    matchLabels:
      app: inventory-service
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              auth-demo/inventory-client: "true"
      ports:
        - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: orders-from-namespace
  namespace: auth-demo
spec:
  podSelector:
    matchLabels:
      app: orders-service
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 8080
